### ISSUE TITLE
Fix ledger send and deposit functions

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#72]
## Description

Fix ledger send and deposit functions to use their own address. 

## TODO

- [x] - Get BTC to see its own ledger address during a transaction, not a blank keystore
- [x] - Ensure ETH is using its own ledger address when processing a transaction
- [x] - ETH transactions should look at the ETH address, not the keystore address when checking gas amount, for Savers
- [x] - Check approve with in ledger screen, using the ledger address, not the keystore address.
- [x] - EVM send screen for keystore tx should be created, so all is the same as they use the same xchainjs interface. 
- [x] - Test BNB sending. 

Will fix https://github.com/asgardex/asgardex-desktop/issues/40. May also fix #59 

Dependant on https://github.com/asgardex/asgardex-desktop/pull/151

**Comment by GrassRootsCrypto** [comment]
Needs to fixed on the xchainjs side

**Comment by GrassRootsCrypto** [comment]
Avax and BSC added

Avav sending works. BSC error as it believes that BSC.BNB is an ERC20

**Comment by GrassRootsCrypto** [comment]
Need to retest avax and bsc

**Comment by GrassRootsCrypto** [comment]
Initial issues completed. More work to come with ledger in the next release.
